In [1]:
import pandas as pd

In [2]:
df =  pd.read_csv("Fake_Real_Data.csv")
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [3]:
df.shape

(9900, 2)

In [4]:
df.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [5]:
df['label_num']  = df['label'].map({'Fake': 0 ,'Real':1})
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [6]:
import spacy
nlp =  spacy.load("en_core_web_lg")

In [7]:
doc = nlp("Top Trump Surrogate brutally stabs hi")
doc.vector

array([-2.28704169e-01,  1.77576348e-01, -7.38544986e-02,  1.36382371e-01,
        1.36595920e-01,  2.55381707e-02,  1.68541148e-01, -7.23456666e-02,
        2.20115170e-01,  1.24573994e+00,  6.77643344e-02, -1.24041498e-01,
       -1.51806340e-01, -1.07748387e-02, -5.83779998e-02,  6.22721650e-02,
       -1.27998933e-01,  1.72201172e-01,  9.26666632e-02, -1.39433341e-02,
       -9.28473249e-02, -1.17619336e-01, -4.25650086e-03, -6.18748255e-02,
       -7.56789744e-03,  1.38267502e-01, -1.66299984e-01,  1.41539782e-01,
        8.03483278e-02, -7.27324784e-02,  2.65433323e-02,  1.44506320e-01,
       -7.42833391e-02,  6.63366690e-02,  3.00466657e-01, -2.13991001e-01,
       -1.53350011e-01,  4.59475033e-02, -8.72981772e-02, -1.54793993e-01,
        1.24000257e-03, -2.31135488e-01, -4.04273272e-02, -1.22215830e-01,
        4.63283807e-02, -1.08305186e-01, -5.71389943e-02, -8.23443308e-02,
        1.35961697e-02,  3.68504971e-02, -4.66177464e-02,  1.88521668e-01,
       -1.37097389e-01, -4.43462729e-02, -3.81989986e-01,  7.92288333e-02,
        1.07540004e-01,  1.14210494e-01, -7.72401616e-02, -1.02189660e-01,
       -2.43168339e-01,  9.73381624e-02, -1.05743343e-02, -2.98843354e-01,
        1.95065007e-01,  1.78027332e-01,  2.34705005e-02,  1.52268991e-01,
        4.03729975e-02, -1.09179996e-01, -1.81248650e-01,  9.42145940e-03,
        5.96766658e-02,  1.72030017e-01, -8.34481642e-02, -1.67102411e-01,
        8.04002807e-02, -1.00847997e-01,  1.22788297e-02, -2.84949988e-02,
       -5.09346724e-02,  8.00766516e-03, -1.81467339e-01,  1.43681169e-01,
       -2.39518285e-02,  2.56631643e-01,  4.74497467e-01, -1.38460010e-01,
       -2.05438305e-02, -1.51444944e-02, -1.55843347e-01,  1.24174990e-01,
        1.78246647e-02, -6.98202252e-02, -4.27799970e-02, -2.48601317e-01,
        1.97779179e-01,  1.61376640e-01, -2.06850007e-01, -3.51864588e-03,
        3.77902649e-02,  1.31583974e-01,  3.32844347e-01,  6.26555011e-02,
       -7.05576986e-02, -1.10808492e+00, -1.08665846e-01, -1.03521504e-01,
        1.74571667e-02, -5.16957045e-02,  4.18790020e-02, -1.48081660e-01,
       -7.66239837e-02, -6.29627630e-02,  1.20974839e-01,  1.38855055e-01,
        1.72378346e-01, -2.06026316e-01,  2.13438328e-02,  6.82018176e-02,
       -1.17894500e-01,  9.06783566e-02,  1.08690001e-01,  1.18565656e-01,
       -9.55091789e-02,  1.78106442e-01,  1.31429983e-02, -1.85743328e-02,
       -3.99923354e-01, -1.32853342e-02, -1.82549000e-01,  9.11481604e-02,
       -8.02131668e-02, -2.84270018e-01, -3.87083292e-02, -1.60786603e-02,
       -6.99276626e-02,  1.57213822e-01,  2.88860109e-02, -3.68466750e-02,
       -1.44973505e+00, -6.41916180e-03, -1.19790666e-01, -1.66928336e-01,
       -1.72624171e-01,  8.70836601e-02, -2.92716697e-02, -1.76953319e-02,
        2.11732164e-01, -1.10939957e-01, -9.30733383e-02,  4.61766720e-02,
        1.42481728e-02,  1.21084988e-01,  6.18032366e-02, -4.92773242e-02,
       -1.29457921e-01,  8.17939863e-02,  1.07891671e-01,  1.51284141e-02,
        9.33678374e-02, -1.10226840e-01,  1.06318332e-01,  2.47112155e-01,
       -1.20213158e-01, -2.52546698e-01, -6.69500008e-02, -3.97532806e-03,
        1.09509341e-01,  1.66031703e-01, -2.56364495e-01, -4.58437987e-02,
        1.96696177e-01,  9.31516290e-03,  8.26310143e-02,  4.11950648e-02,
       -5.26264906e-02, -1.22913487e-01,  6.63433373e-02,  5.63936643e-02,
        1.33141339e-01, -1.70062497e-01, -8.84050056e-02,  3.31774950e-02,
        2.60913998e-01,  2.43961677e-01,  2.46978343e-01, -1.00760818e-01,
       -1.35186374e-01, -1.33561835e-01,  4.39096689e-02, -5.26449978e-02,
       -5.94615079e-02, -2.76549999e-02,  2.72515025e-02, -1.22416995e-01,
       -1.68173328e-01, -2.49664988e-02,  1.43461660e-01, -9.72566828e-02,
       -1.22498333e-01, -2.06094682e-01, -2.11619496e-01, -1.66103199e-01,
       -1.42216682e-03, -7.51820505e-02,  8.42683315e-02,  7.82763287e-02,
       -8.26263353e-02, -1.56387925e-01, -2.93585688e-01, -1.10654831e-01,
       -1.81353331e-01, -7.01315030e-02, -3.38299982e-02, -1.73336491e-02,
        6.01948313e-02,  4.55104150e-02, -1.95798427e-02, -1.96470499e-01,
       -1.72077835e-01,  2.32906505e-01, -2.94543263e-02,  4.85446639e-02,
        1.92903459e-01,  2.43538007e-01,  7.62449875e-02,  7.86213279e-02,
        5.49231656e-02, -1.87434986e-01, -7.94795379e-02, -1.63063332e-01,
       -6.79093301e-02,  2.65548322e-02, -1.37539327e-01, -1.58244506e-01,
       -2.11658314e-01,  8.70969426e-03,  1.08180828e-01, -4.43976559e-02,
        7.70493224e-02, -8.54486749e-02, -7.12720081e-02,  2.03633364e-02,
        1.64181337e-01, -7.39448294e-02,  1.13439679e-01, -1.65781900e-01,
        2.97481507e-01,  7.73215070e-02, -2.16350496e-01,  6.50509968e-02,
       -7.80613348e-02, -1.81011662e-01, -1.41844004e-01, -1.03402495e-01,
       -8.99953246e-02, -5.73633313e-02, -6.32280037e-02, -1.75644994e-01,
       -2.13563010e-01, -1.42022669e-02, -1.52177498e-01,  1.63378343e-02,
       -1.75883174e-01,  1.14993162e-01, -1.47346988e-01,  3.52053232e-02,
       -2.07339957e-01, -2.86528487e-02, -2.63806164e-01, -1.24656655e-01,
       -1.70799941e-02,  1.73829988e-01,  7.89243281e-02, -2.57295053e-02,
        1.39514551e-01, -7.21559972e-02,  7.48349950e-02,  4.67862003e-02,
        1.67729005e-01,  1.11985661e-01, -3.55266524e-03, -4.91933757e-03,
       -1.21422499e-01,  3.39234956e-02, -2.27955341e-01, -1.03738166e-01,
       -5.81639893e-02,  2.25066692e-02,  1.97123662e-01, -1.30660340e-01,
       -2.36169994e-01, -1.02560841e-01, -2.72630062e-02,  5.44870012e-02,
       -2.45271344e-02, -1.05030663e-01,  6.10001720e-02,  2.46441662e-02],
      dtype=float32)

In [8]:
df['vector'] = df['Text'].apply(lambda text: nlp(text).vector)

In [9]:
df.head()

,Text,label,label_num,vector
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,0,"[-0.103623025, 0.17802684, -0.11873861, -0.034..."
1,U.S. conservative leader optimistic of common ...,Real,1,"[-0.0063406364, 0.16712041, -0.06661373, 0.017..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,1,"[-0.122753024, 0.17192385, -0.024732638, -0.06..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,0,"[-0.027337318, 0.12501417, -0.0073965387, -0.0..."
4,Democrats say Trump agrees to work on immigrat...,Real,1,"[-0.032708026, 0.093958504, -0.03287002, -0.00..."

In [10]:
df.drop(["Text","label"], axis = 1, inplace = True)
df.head()

   label_num                                             vector
0          0  [-0.103623025, 0.17802684, -0.11873861, -0.034...
1          1  [-0.0063406364, 0.16712041, -0.06661373, 0.017...
2          1  [-0.122753024, 0.17192385, -0.024732638, -0.06...
3          0  [-0.027337318, 0.12501417, -0.0073965387, -0.0...
4          1  [-0.032708026, 0.093958504, -0.03287002, -0.00...

In [11]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(
    df.vector, 
    df.label_num,
    test_size=0.2,
    random_state=2022
)

In [16]:
X_train.shape

(7920,)